
(defun c:remove-last-point ( / __strata_index)
	(setq *section_points_x (cdr *section_points_x))
	(setq *ground_points (cdr *ground_points))
  (setq __strata_index  0)
  (while (< __strata_index *strata_count)
    (set (read (strcat "strata_points_" (itoa __strata_index)))
     		 (cdr (eval (read (strcat "strata_points_" (itoa __strata_index))))))
  	(setq __strata_index (1+ __strata_index)) 
  )
)